spring:
  datasource:
    driver-class-name: ${datasource.prod-driver-class-name}
    username: ${datasource.prod-username}
    password: ${datasource.prod-password}
    url: ${datasource.prod-url}
oauth:
  apple:
    client-id: com.twohosun.TwoHoSun

file:
  dir: /home/ubuntu/images/