spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${oauth.apple.client-id}
            redirect-uri: https://${base-uri}/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
