spring:
  sql:
    init:
      schema-locations: classpath:static/schema.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    defer-datasource-initialization: true