spring:
  application:
    name: twoHoSeon
  profiles:
    active: local
    group:
      local:
        - dev
        - common
        - config
        - server
        - db
        - security
        - upload
        - quartz
      prod:
        - prod
        - common
        - config
        - server
        - db
        - security
        - upload
        - quartz