spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: ${datasource.dev-driver-class-name}
    url: ${datasource.dev-url}
    username: ${datasource.dev-username}
    password: ${datasource.dev-password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
oauth:
  apple:
    client-id: com.twohosun.service
server:
  port: 443
  ssl:
    key-store: ${ssl.dev.key-store}
    key-store-password: ${ssl.dev.key-store-password}
    key-store-type: ${ssl.dev.key-store-type}
file:
  dir: ${app.upload.dev-path}
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.web: debug
    com.twohoseon.app: debug