spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: ${datasource.dev-driver-class-name}
    url: ${datasource.dev-url}
    username: ${datasource.dev-username}
    password: ${datasource.dev-password}
oauth:
  apple:
    client-id: com.twohosun.service
server:
  port: 443
  ssl:
    key-store: ${ssl.dev.key-store}
    key-store-password: ${ssl.dev.key-store-password}
    key-store-type: ${ssl.dev.key-store-type}
file:
  dir: ${app.upload.dev-path}